# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: babe29f877169f09dce1a0281ce769f162c5a49218cade8f17a0e8c4afb01a1462f574bd3ed5120ef5091c9161aa3600f5f90fcea2a8aa54954247b2ffa90692

test:
  secret_key_base: 1c6b899d3719cc86d95deaed14543645711cf919de5fb2527a64585019b2f5c9b8d7a72fcc69ae271922743a8047b8b4a42218f4d33df51b4755156d7420e3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
